name: Safe Secret Runtime Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_VALUE: ${{ secrets.SECRET_CONFIG_FILE }}

    steps:
      - uses: actions/checkout@v4

      - name: Compile App (No secret inside)
        run: g++ main.cpp -o myapp

      - name: Run App (reads secret from env at runtime)
        run: ./myapp
