name: Safe Secret Runtime Test

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_VALUE: ${{ secrets.SECRET_CONFIG_FILE }}

    steps:
      - uses: actions/checkout@v4

      - name: Compile App
        run: g++ main.cpp -o myapp

      - name: Run App
        run: ./myapp
