name: Inject Secret at Runtime Only

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Secret File at Runtime
        run: |
          echo "${{ secrets.SECRET_CONFIG_FILE }}" > secret_config.cpp
          echo "Secret file written."

      - name: Compile App
        run: g++ main.cpp -o myapp

      - name: Run App
        run: ./myapp

      - name: Cleanup
        run: rm -f secret_config.cpp
