name: Secure Runtime Secret Test

on:
  workflow_dispatch:  # manually triggered

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile without secrets
        run: g++ main.cpp -o test-app

      - name: Run App with injected secret
        run: ./test-app
