name: Test Secret File Injection

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-secret-injection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Secret File at Runtime
        run: |
          echo "${{ secrets.SECRET_CONFIG_FILE }}" > secret_config.cpp
          echo "Secret file written at runtime ✅"

      - name: Compile
        run: g++ main.cpp -o test-app

      - name: Run App
        run: ./test-app
